//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ServicioLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clLogin", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class clLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioLogin.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento objC del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLogi", ReplyAction="*")]
        Web.ServicioLogin.mtdLogiResponse mtdLogi(Web.ServicioLogin.mtdLogiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLogi", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.ServicioLogin.mtdLogiResponse> mtdLogiAsync(Web.ServicioLogin.mtdLogiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdLogiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdLogi", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServicioLogin.mtdLogiRequestBody Body;
        
        public mtdLogiRequest() {
        }
        
        public mtdLogiRequest(Web.ServicioLogin.mtdLogiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdLogiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.ServicioLogin.clLogin objC;
        
        public mtdLogiRequestBody() {
        }
        
        public mtdLogiRequestBody(Web.ServicioLogin.clLogin objC) {
            this.objC = objC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdLogiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdLogiResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServicioLogin.mtdLogiResponseBody Body;
        
        public mtdLogiResponse() {
        }
        
        public mtdLogiResponse(Web.ServicioLogin.mtdLogiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdLogiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mtdLogiResult;
        
        public mtdLogiResponseBody() {
        }
        
        public mtdLogiResponseBody(int mtdLogiResult) {
            this.mtdLogiResult = mtdLogiResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Web.ServicioLogin.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Web.ServicioLogin.WebService1Soap>, Web.ServicioLogin.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.ServicioLogin.mtdLogiResponse Web.ServicioLogin.WebService1Soap.mtdLogi(Web.ServicioLogin.mtdLogiRequest request) {
            return base.Channel.mtdLogi(request);
        }
        
        public int mtdLogi(Web.ServicioLogin.clLogin objC) {
            Web.ServicioLogin.mtdLogiRequest inValue = new Web.ServicioLogin.mtdLogiRequest();
            inValue.Body = new Web.ServicioLogin.mtdLogiRequestBody();
            inValue.Body.objC = objC;
            Web.ServicioLogin.mtdLogiResponse retVal = ((Web.ServicioLogin.WebService1Soap)(this)).mtdLogi(inValue);
            return retVal.Body.mtdLogiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.ServicioLogin.mtdLogiResponse> Web.ServicioLogin.WebService1Soap.mtdLogiAsync(Web.ServicioLogin.mtdLogiRequest request) {
            return base.Channel.mtdLogiAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.ServicioLogin.mtdLogiResponse> mtdLogiAsync(Web.ServicioLogin.clLogin objC) {
            Web.ServicioLogin.mtdLogiRequest inValue = new Web.ServicioLogin.mtdLogiRequest();
            inValue.Body = new Web.ServicioLogin.mtdLogiRequestBody();
            inValue.Body.objC = objC;
            return ((Web.ServicioLogin.WebService1Soap)(this)).mtdLogiAsync(inValue);
        }
    }
}
