//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ServicioOscar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clUsuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class clUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        private int IdRolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clTerreno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class clTerreno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTerrenoField;
        
        private double LargoField;
        
        private double AnchoField;
        
        private int IdUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTerreno {
            get {
                return this.IdTerrenoField;
            }
            set {
                if ((this.IdTerrenoField.Equals(value) != true)) {
                    this.IdTerrenoField = value;
                    this.RaisePropertyChanged("IdTerreno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Largo {
            get {
                return this.LargoField;
            }
            set {
                if ((this.LargoField.Equals(value) != true)) {
                    this.LargoField = value;
                    this.RaisePropertyChanged("Largo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Ancho {
            get {
                return this.AnchoField;
            }
            set {
                if ((this.AnchoField.Equals(value) != true)) {
                    this.AnchoField = value;
                    this.RaisePropertyChanged("Ancho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioOscar.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento objUsu del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarUsuarios", ReplyAction="*")]
        Web.ServicioOscar.mtdEditarUsuariosResponse mtdEditarUsuarios(Web.ServicioOscar.mtdEditarUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.ServicioOscar.mtdEditarUsuariosResponse> mtdEditarUsuariosAsync(Web.ServicioOscar.mtdEditarUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento objTerr del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarTerreno", ReplyAction="*")]
        Web.ServicioOscar.mtdRegistrarTerrenoResponse mtdRegistrarTerreno(Web.ServicioOscar.mtdRegistrarTerrenoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarTerreno", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.ServicioOscar.mtdRegistrarTerrenoResponse> mtdRegistrarTerrenoAsync(Web.ServicioOscar.mtdRegistrarTerrenoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdEditarUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdEditarUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServicioOscar.mtdEditarUsuariosRequestBody Body;
        
        public mtdEditarUsuariosRequest() {
        }
        
        public mtdEditarUsuariosRequest(Web.ServicioOscar.mtdEditarUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdEditarUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.ServicioOscar.clUsuario objUsu;
        
        public mtdEditarUsuariosRequestBody() {
        }
        
        public mtdEditarUsuariosRequestBody(Web.ServicioOscar.clUsuario objUsu) {
            this.objUsu = objUsu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdEditarUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdEditarUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServicioOscar.mtdEditarUsuariosResponseBody Body;
        
        public mtdEditarUsuariosResponse() {
        }
        
        public mtdEditarUsuariosResponse(Web.ServicioOscar.mtdEditarUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdEditarUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mtdEditarUsuariosResult;
        
        public mtdEditarUsuariosResponseBody() {
        }
        
        public mtdEditarUsuariosResponseBody(int mtdEditarUsuariosResult) {
            this.mtdEditarUsuariosResult = mtdEditarUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdRegistrarTerrenoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdRegistrarTerreno", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServicioOscar.mtdRegistrarTerrenoRequestBody Body;
        
        public mtdRegistrarTerrenoRequest() {
        }
        
        public mtdRegistrarTerrenoRequest(Web.ServicioOscar.mtdRegistrarTerrenoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdRegistrarTerrenoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web.ServicioOscar.clTerreno objTerr;
        
        public mtdRegistrarTerrenoRequestBody() {
        }
        
        public mtdRegistrarTerrenoRequestBody(Web.ServicioOscar.clTerreno objTerr) {
            this.objTerr = objTerr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mtdRegistrarTerrenoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mtdRegistrarTerrenoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.ServicioOscar.mtdRegistrarTerrenoResponseBody Body;
        
        public mtdRegistrarTerrenoResponse() {
        }
        
        public mtdRegistrarTerrenoResponse(Web.ServicioOscar.mtdRegistrarTerrenoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mtdRegistrarTerrenoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int mtdRegistrarTerrenoResult;
        
        public mtdRegistrarTerrenoResponseBody() {
        }
        
        public mtdRegistrarTerrenoResponseBody(int mtdRegistrarTerrenoResult) {
            this.mtdRegistrarTerrenoResult = mtdRegistrarTerrenoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Web.ServicioOscar.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Web.ServicioOscar.WebService1Soap>, Web.ServicioOscar.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.ServicioOscar.mtdEditarUsuariosResponse Web.ServicioOscar.WebService1Soap.mtdEditarUsuarios(Web.ServicioOscar.mtdEditarUsuariosRequest request) {
            return base.Channel.mtdEditarUsuarios(request);
        }
        
        public int mtdEditarUsuarios(Web.ServicioOscar.clUsuario objUsu) {
            Web.ServicioOscar.mtdEditarUsuariosRequest inValue = new Web.ServicioOscar.mtdEditarUsuariosRequest();
            inValue.Body = new Web.ServicioOscar.mtdEditarUsuariosRequestBody();
            inValue.Body.objUsu = objUsu;
            Web.ServicioOscar.mtdEditarUsuariosResponse retVal = ((Web.ServicioOscar.WebService1Soap)(this)).mtdEditarUsuarios(inValue);
            return retVal.Body.mtdEditarUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.ServicioOscar.mtdEditarUsuariosResponse> Web.ServicioOscar.WebService1Soap.mtdEditarUsuariosAsync(Web.ServicioOscar.mtdEditarUsuariosRequest request) {
            return base.Channel.mtdEditarUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.ServicioOscar.mtdEditarUsuariosResponse> mtdEditarUsuariosAsync(Web.ServicioOscar.clUsuario objUsu) {
            Web.ServicioOscar.mtdEditarUsuariosRequest inValue = new Web.ServicioOscar.mtdEditarUsuariosRequest();
            inValue.Body = new Web.ServicioOscar.mtdEditarUsuariosRequestBody();
            inValue.Body.objUsu = objUsu;
            return ((Web.ServicioOscar.WebService1Soap)(this)).mtdEditarUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.ServicioOscar.mtdRegistrarTerrenoResponse Web.ServicioOscar.WebService1Soap.mtdRegistrarTerreno(Web.ServicioOscar.mtdRegistrarTerrenoRequest request) {
            return base.Channel.mtdRegistrarTerreno(request);
        }
        
        public int mtdRegistrarTerreno(Web.ServicioOscar.clTerreno objTerr) {
            Web.ServicioOscar.mtdRegistrarTerrenoRequest inValue = new Web.ServicioOscar.mtdRegistrarTerrenoRequest();
            inValue.Body = new Web.ServicioOscar.mtdRegistrarTerrenoRequestBody();
            inValue.Body.objTerr = objTerr;
            Web.ServicioOscar.mtdRegistrarTerrenoResponse retVal = ((Web.ServicioOscar.WebService1Soap)(this)).mtdRegistrarTerreno(inValue);
            return retVal.Body.mtdRegistrarTerrenoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.ServicioOscar.mtdRegistrarTerrenoResponse> Web.ServicioOscar.WebService1Soap.mtdRegistrarTerrenoAsync(Web.ServicioOscar.mtdRegistrarTerrenoRequest request) {
            return base.Channel.mtdRegistrarTerrenoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.ServicioOscar.mtdRegistrarTerrenoResponse> mtdRegistrarTerrenoAsync(Web.ServicioOscar.clTerreno objTerr) {
            Web.ServicioOscar.mtdRegistrarTerrenoRequest inValue = new Web.ServicioOscar.mtdRegistrarTerrenoRequest();
            inValue.Body = new Web.ServicioOscar.mtdRegistrarTerrenoRequestBody();
            inValue.Body.objTerr = objTerr;
            return ((Web.ServicioOscar.WebService1Soap)(this)).mtdRegistrarTerrenoAsync(inValue);
        }
    }
}
