//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.ServicioOscar {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioOscar.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarRol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarRol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarRol", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarRolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarUsuario(Web.ServicioOscar.clUsuario objUsu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarUsuarioAsync(Web.ServicioOscar.clUsuario objUsu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdEditarUsuarios(Web.ServicioOscar.clUsuario objUsu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdEditarUsuariosAsync(Web.ServicioOscar.clUsuario objUsu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarTerreno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarTerreno(Web.ServicioOscar.clTerreno objTerr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarTerreno", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarTerrenoAsync(Web.ServicioOscar.clTerreno objTerr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarSuelos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarSuelos(Web.ServicioOscar.clSuelos objSuelos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarSuelos", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarSuelosAsync(Web.ServicioOscar.clSuelos objSuelos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarSuelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarSuelo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarSuelo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarSueloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdLogin(string Correo, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdLoginAsync(string Correo, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEnviarID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdEnviarID(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEnviarID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdEnviarIDAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdBuscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdBuscar(Web.ServicioOscar.clUsuario objUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdBuscarAsync(Web.ServicioOscar.clUsuario objUsua);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarProducto(Web.ServicioOscar.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarProductoAsync(Web.ServicioOscar.clProducto objPro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarFases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarFases();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarFases", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarFasesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarFase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdEditarFase(Web.ServicioOscar.clFases objFas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarFase", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdEditarFaseAsync(Web.ServicioOscar.clFases objFas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarTerreno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdEditarTerreno(Web.ServicioOscar.clTerreno objT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEditarTerreno", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdEditarTerrenoAsync(Web.ServicioOscar.clTerreno objT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdBuscarTerreno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdBuscarTerreno(Web.ServicioOscar.clTerreno objTerreno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdBuscarTerreno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdBuscarTerrenoAsync(Web.ServicioOscar.clTerreno objTerreno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdfecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdfecha();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdfecha", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdfechaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarPregunta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarPregunta(Web.ServicioOscar.clPregunta objPre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarPregunta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarPreguntaAsync(Web.ServicioOscar.clPregunta objPre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarPregunta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarPregunta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarPregunta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarPreguntaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarRespuesta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarRespuesta(Web.ServicioOscar.clRespuesta objRes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarRespuesta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarRespuestaAsync(Web.ServicioOscar.clRespuesta objRes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarEtapa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarEtapa(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarEtapa", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarEtapaAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarInsumos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarInsumos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarInsumos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarInsumosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarInsumo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarInsumo(Web.ServicioOscar.clInsumo objIns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarInsumo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarInsumoAsync(Web.ServicioOscar.clInsumo objIns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarInterno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdListarInterno(Web.ServicioOscar.clInterno ObjInterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdListarInterno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdListarInternoAsync(Web.ServicioOscar.clInterno ObjInterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarInterno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdRegistrarInterno(Web.ServicioOscar.clInterno objIns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdRegistrarInterno", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdRegistrarInternoAsync(Web.ServicioOscar.clInterno objIns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdTerrenoEtapas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int mtdTerrenoEtapas(Web.ServicioOscar.clTerreno objTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdTerrenoEtapas", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mtdTerrenoEtapasAsync(Web.ServicioOscar.clTerreno objTe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEtapaTerreno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdEtapaTerreno(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdEtapaTerreno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdEtapaTerrenoAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdInternoCultivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet mtdInternoCultivo(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mtdInternoCultivo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> mtdInternoCultivoAsync(int x);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idUsuarioField;
        
        private string documentoField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string correoField;
        
        private string claveField;
        
        private string numeroField;
        
        private int idRolField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("Documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("Apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("Correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int IdRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
                this.RaisePropertyChanged("IdRol");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clInterno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool chField;
        
        private int idInternoField;
        
        private int idEtapaField;
        
        private string faseField;
        
        private int diasField;
        
        private bool checkField;
        
        private int idTerrenoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ch {
            get {
                return this.chField;
            }
            set {
                this.chField = value;
                this.RaisePropertyChanged("ch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdInterno {
            get {
                return this.idInternoField;
            }
            set {
                this.idInternoField = value;
                this.RaisePropertyChanged("IdInterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int IdEtapa {
            get {
                return this.idEtapaField;
            }
            set {
                this.idEtapaField = value;
                this.RaisePropertyChanged("IdEtapa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Fase {
            get {
                return this.faseField;
            }
            set {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int Dias {
            get {
                return this.diasField;
            }
            set {
                this.diasField = value;
                this.RaisePropertyChanged("Dias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Check {
            get {
                return this.checkField;
            }
            set {
                this.checkField = value;
                this.RaisePropertyChanged("Check");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IdTerreno {
            get {
                return this.idTerrenoField;
            }
            set {
                this.idTerrenoField = value;
                this.RaisePropertyChanged("IdTerreno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clInsumo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idInsumoField;
        
        private string nombreField;
        
        private string fotoField;
        
        private string descripcionField;
        
        private int idTipoInsumoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdInsumo {
            get {
                return this.idInsumoField;
            }
            set {
                this.idInsumoField = value;
                this.RaisePropertyChanged("IdInsumo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("Foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdTipoInsumo {
            get {
                return this.idTipoInsumoField;
            }
            set {
                this.idTipoInsumoField = value;
                this.RaisePropertyChanged("IdTipoInsumo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idRespuestaField;
        
        private string respuestaField;
        
        private string fechaRField;
        
        private int idUsuarioField;
        
        private int idPreguntaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                this.idRespuestaField = value;
                this.RaisePropertyChanged("IdRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FechaR {
            get {
                return this.fechaRField;
            }
            set {
                this.fechaRField = value;
                this.RaisePropertyChanged("FechaR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdPregunta {
            get {
                return this.idPreguntaField;
            }
            set {
                this.idPreguntaField = value;
                this.RaisePropertyChanged("IdPregunta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clPregunta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idPreguntaField;
        
        private string preguntaField;
        
        private string fechaPField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdPregunta {
            get {
                return this.idPreguntaField;
            }
            set {
                this.idPreguntaField = value;
                this.RaisePropertyChanged("IdPregunta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
                this.RaisePropertyChanged("Pregunta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FechaP {
            get {
                return this.fechaPField;
            }
            set {
                this.fechaPField = value;
                this.RaisePropertyChanged("FechaP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clFases : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idFaseField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string fotoField;
        
        private string duracionField;
        
        private string fechaInicioField;
        
        private string fechaFinalField;
        
        private int idEtapasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdFase {
            get {
                return this.idFaseField;
            }
            set {
                this.idFaseField = value;
                this.RaisePropertyChanged("IdFase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("Foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("Duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("FechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
                this.RaisePropertyChanged("FechaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int IdEtapas {
            get {
                return this.idEtapasField;
            }
            set {
                this.idEtapasField = value;
                this.RaisePropertyChanged("IdEtapas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProductoField;
        
        private string nombrePField;
        
        private int cantidadField;
        
        private int idEtapaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("IdProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreP {
            get {
                return this.nombrePField;
            }
            set {
                this.nombrePField = value;
                this.RaisePropertyChanged("NombreP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int IdEtapa {
            get {
                return this.idEtapaField;
            }
            set {
                this.idEtapaField = value;
                this.RaisePropertyChanged("IdEtapa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clSuelos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double acidezOalcalinidadField;
        
        private double aluminioField;
        
        private double nitrógenoField;
        
        private double potasioField;
        
        private double fósforoField;
        
        private double calcioField;
        
        private double magnesioField;
        
        private double azufreField;
        
        private double cobreField;
        
        private double cincField;
        
        private double manganesoField;
        
        private double boroField;
        
        private int idTipoSueloField;
        
        private int idCultivoField;
        
        private int idTerrenoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double AcidezOalcalinidad {
            get {
                return this.acidezOalcalinidadField;
            }
            set {
                this.acidezOalcalinidadField = value;
                this.RaisePropertyChanged("AcidezOalcalinidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Aluminio {
            get {
                return this.aluminioField;
            }
            set {
                this.aluminioField = value;
                this.RaisePropertyChanged("Aluminio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Nitrógeno {
            get {
                return this.nitrógenoField;
            }
            set {
                this.nitrógenoField = value;
                this.RaisePropertyChanged("Nitrógeno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Potasio {
            get {
                return this.potasioField;
            }
            set {
                this.potasioField = value;
                this.RaisePropertyChanged("Potasio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double Fósforo {
            get {
                return this.fósforoField;
            }
            set {
                this.fósforoField = value;
                this.RaisePropertyChanged("Fósforo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double Calcio {
            get {
                return this.calcioField;
            }
            set {
                this.calcioField = value;
                this.RaisePropertyChanged("Calcio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Magnesio {
            get {
                return this.magnesioField;
            }
            set {
                this.magnesioField = value;
                this.RaisePropertyChanged("Magnesio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Azufre {
            get {
                return this.azufreField;
            }
            set {
                this.azufreField = value;
                this.RaisePropertyChanged("Azufre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double Cobre {
            get {
                return this.cobreField;
            }
            set {
                this.cobreField = value;
                this.RaisePropertyChanged("Cobre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double Cinc {
            get {
                return this.cincField;
            }
            set {
                this.cincField = value;
                this.RaisePropertyChanged("Cinc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double Manganeso {
            get {
                return this.manganesoField;
            }
            set {
                this.manganesoField = value;
                this.RaisePropertyChanged("Manganeso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double Boro {
            get {
                return this.boroField;
            }
            set {
                this.boroField = value;
                this.RaisePropertyChanged("Boro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int IdTipoSuelo {
            get {
                return this.idTipoSueloField;
            }
            set {
                this.idTipoSueloField = value;
                this.RaisePropertyChanged("IdTipoSuelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int IdCultivo {
            get {
                return this.idCultivoField;
            }
            set {
                this.idCultivoField = value;
                this.RaisePropertyChanged("IdCultivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int IdTerreno {
            get {
                return this.idTerrenoField;
            }
            set {
                this.idTerrenoField = value;
                this.RaisePropertyChanged("IdTerreno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clTerreno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTerrenoField;
        
        private string nombreTerrenoField;
        
        private double largoField;
        
        private double anchoField;
        
        private int idUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdTerreno {
            get {
                return this.idTerrenoField;
            }
            set {
                this.idTerrenoField = value;
                this.RaisePropertyChanged("IdTerreno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreTerreno {
            get {
                return this.nombreTerrenoField;
            }
            set {
                this.nombreTerrenoField = value;
                this.RaisePropertyChanged("NombreTerreno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("Largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("Ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("IdUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Web.ServicioOscar.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Web.ServicioOscar.WebService1Soap>, Web.ServicioOscar.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet mtdListarRol() {
            return base.Channel.mtdListarRol();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarRolAsync() {
            return base.Channel.mtdListarRolAsync();
        }
        
        public int mtdRegistrarUsuario(Web.ServicioOscar.clUsuario objUsu) {
            return base.Channel.mtdRegistrarUsuario(objUsu);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarUsuarioAsync(Web.ServicioOscar.clUsuario objUsu) {
            return base.Channel.mtdRegistrarUsuarioAsync(objUsu);
        }
        
        public int mtdEditarUsuarios(Web.ServicioOscar.clUsuario objUsu) {
            return base.Channel.mtdEditarUsuarios(objUsu);
        }
        
        public System.Threading.Tasks.Task<int> mtdEditarUsuariosAsync(Web.ServicioOscar.clUsuario objUsu) {
            return base.Channel.mtdEditarUsuariosAsync(objUsu);
        }
        
        public int mtdRegistrarTerreno(Web.ServicioOscar.clTerreno objTerr) {
            return base.Channel.mtdRegistrarTerreno(objTerr);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarTerrenoAsync(Web.ServicioOscar.clTerreno objTerr) {
            return base.Channel.mtdRegistrarTerrenoAsync(objTerr);
        }
        
        public int mtdRegistrarSuelos(Web.ServicioOscar.clSuelos objSuelos) {
            return base.Channel.mtdRegistrarSuelos(objSuelos);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarSuelosAsync(Web.ServicioOscar.clSuelos objSuelos) {
            return base.Channel.mtdRegistrarSuelosAsync(objSuelos);
        }
        
        public System.Data.DataSet mtdListarSuelo() {
            return base.Channel.mtdListarSuelo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarSueloAsync() {
            return base.Channel.mtdListarSueloAsync();
        }
        
        public int mtdLogin(string Correo, string Clave) {
            return base.Channel.mtdLogin(Correo, Clave);
        }
        
        public System.Threading.Tasks.Task<int> mtdLoginAsync(string Correo, string Clave) {
            return base.Channel.mtdLoginAsync(Correo, Clave);
        }
        
        public System.Data.DataSet mtdEnviarID(int x) {
            return base.Channel.mtdEnviarID(x);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdEnviarIDAsync(int x) {
            return base.Channel.mtdEnviarIDAsync(x);
        }
        
        public System.Data.DataSet mtdBuscar(Web.ServicioOscar.clUsuario objUsua) {
            return base.Channel.mtdBuscar(objUsua);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdBuscarAsync(Web.ServicioOscar.clUsuario objUsua) {
            return base.Channel.mtdBuscarAsync(objUsua);
        }
        
        public int mtdRegistrarProducto(Web.ServicioOscar.clProducto objPro) {
            return base.Channel.mtdRegistrarProducto(objPro);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarProductoAsync(Web.ServicioOscar.clProducto objPro) {
            return base.Channel.mtdRegistrarProductoAsync(objPro);
        }
        
        public System.Data.DataSet mtdListarFases() {
            return base.Channel.mtdListarFases();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarFasesAsync() {
            return base.Channel.mtdListarFasesAsync();
        }
        
        public int mtdEditarFase(Web.ServicioOscar.clFases objFas) {
            return base.Channel.mtdEditarFase(objFas);
        }
        
        public System.Threading.Tasks.Task<int> mtdEditarFaseAsync(Web.ServicioOscar.clFases objFas) {
            return base.Channel.mtdEditarFaseAsync(objFas);
        }
        
        public int mtdEditarTerreno(Web.ServicioOscar.clTerreno objT) {
            return base.Channel.mtdEditarTerreno(objT);
        }
        
        public System.Threading.Tasks.Task<int> mtdEditarTerrenoAsync(Web.ServicioOscar.clTerreno objT) {
            return base.Channel.mtdEditarTerrenoAsync(objT);
        }
        
        public System.Data.DataSet mtdBuscarTerreno(Web.ServicioOscar.clTerreno objTerreno) {
            return base.Channel.mtdBuscarTerreno(objTerreno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdBuscarTerrenoAsync(Web.ServicioOscar.clTerreno objTerreno) {
            return base.Channel.mtdBuscarTerrenoAsync(objTerreno);
        }
        
        public System.Data.DataSet mtdfecha() {
            return base.Channel.mtdfecha();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdfechaAsync() {
            return base.Channel.mtdfechaAsync();
        }
        
        public int mtdRegistrarPregunta(Web.ServicioOscar.clPregunta objPre) {
            return base.Channel.mtdRegistrarPregunta(objPre);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarPreguntaAsync(Web.ServicioOscar.clPregunta objPre) {
            return base.Channel.mtdRegistrarPreguntaAsync(objPre);
        }
        
        public System.Data.DataSet mtdListarPregunta() {
            return base.Channel.mtdListarPregunta();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarPreguntaAsync() {
            return base.Channel.mtdListarPreguntaAsync();
        }
        
        public int mtdRegistrarRespuesta(Web.ServicioOscar.clRespuesta objRes) {
            return base.Channel.mtdRegistrarRespuesta(objRes);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarRespuestaAsync(Web.ServicioOscar.clRespuesta objRes) {
            return base.Channel.mtdRegistrarRespuestaAsync(objRes);
        }
        
        public System.Data.DataSet mtdListarEtapa(int x) {
            return base.Channel.mtdListarEtapa(x);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarEtapaAsync(int x) {
            return base.Channel.mtdListarEtapaAsync(x);
        }
        
        public System.Data.DataSet mtdListarInsumos() {
            return base.Channel.mtdListarInsumos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarInsumosAsync() {
            return base.Channel.mtdListarInsumosAsync();
        }
        
        public int mtdRegistrarInsumo(Web.ServicioOscar.clInsumo objIns) {
            return base.Channel.mtdRegistrarInsumo(objIns);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarInsumoAsync(Web.ServicioOscar.clInsumo objIns) {
            return base.Channel.mtdRegistrarInsumoAsync(objIns);
        }
        
        public System.Data.DataSet mtdListarInterno(Web.ServicioOscar.clInterno ObjInterno) {
            return base.Channel.mtdListarInterno(ObjInterno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdListarInternoAsync(Web.ServicioOscar.clInterno ObjInterno) {
            return base.Channel.mtdListarInternoAsync(ObjInterno);
        }
        
        public int mtdRegistrarInterno(Web.ServicioOscar.clInterno objIns) {
            return base.Channel.mtdRegistrarInterno(objIns);
        }
        
        public System.Threading.Tasks.Task<int> mtdRegistrarInternoAsync(Web.ServicioOscar.clInterno objIns) {
            return base.Channel.mtdRegistrarInternoAsync(objIns);
        }
        
        public int mtdTerrenoEtapas(Web.ServicioOscar.clTerreno objTe) {
            return base.Channel.mtdTerrenoEtapas(objTe);
        }
        
        public System.Threading.Tasks.Task<int> mtdTerrenoEtapasAsync(Web.ServicioOscar.clTerreno objTe) {
            return base.Channel.mtdTerrenoEtapasAsync(objTe);
        }
        
        public System.Data.DataSet mtdEtapaTerreno(int x) {
            return base.Channel.mtdEtapaTerreno(x);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdEtapaTerrenoAsync(int x) {
            return base.Channel.mtdEtapaTerrenoAsync(x);
        }
        
        public System.Data.DataSet mtdInternoCultivo(int x) {
            return base.Channel.mtdInternoCultivo(x);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> mtdInternoCultivoAsync(int x) {
            return base.Channel.mtdInternoCultivoAsync(x);
        }
    }
}
